from graphlib.metrics.paths.astar import AStarShortestPathMetric
from graphlib.metrics.paths.euclidian import EuclidianDistanceShortestPathMetric
from graphlib.metrics.paths.dijkstra import DijkstraShortestPathMetric